[0m21:08:04.124936 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105bf4820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1069c5fc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1069c58a0>]}


============================== 21:08:04.127839 | fe9787a3-516d-4293-b525-c95f302ddaa5 ==============================
[0m21:08:04.127839 [info ] [MainThread]: Running with dbt=1.9.1
[0m21:08:04.128185 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/howeijian/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:08:04.138717 [info ] [MainThread]: dbt version: 1.9.1
[0m21:08:04.139001 [info ] [MainThread]: python version: 3.10.8
[0m21:08:04.139173 [info ] [MainThread]: python path: /Users/howeijian/miniconda3/bin/python
[0m21:08:04.139337 [info ] [MainThread]: os info: macOS-15.1.1-arm64-arm-64bit
[0m21:08:04.768181 [info ] [MainThread]: Using profiles dir at /Users/howeijian/.dbt
[0m21:08:04.768483 [info ] [MainThread]: Using profiles.yml file at /Users/howeijian/.dbt/profiles.yml
[0m21:08:04.768663 [info ] [MainThread]: Using dbt_project.yml file at /Users/howeijian/dbt-dag/dbt_project.yml
[0m21:08:04.768870 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m21:08:04.770616 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.68869716, "process_in_blocks": "0", "process_kernel_time": 0.28667, "process_mem_max_rss": "171032576", "process_out_blocks": "0", "process_user_time": 3.211035}
[0m21:08:04.770906 [debug] [MainThread]: Command `dbt debug` failed at 21:08:04.770862 after 0.69 seconds
[0m21:08:04.771101 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105bf4820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a22020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11ba3f5e0>]}
[0m21:08:04.771308 [debug] [MainThread]: Flushing usage events
[0m21:08:05.941025 [debug] [MainThread]: An error was encountered while trying to flush usage events
